=== alextrukhin/web_module_1/Module_1_Lab_2_Trukhin_SE-324B/part3/passports.dtd
<!-- Definition of the root element 'passports' -->
<!ELEMENT passports (passport+)>

<!-- Definition of passport element and its attributes -->
<!ELEMENT passport (firstName, lastName, patronymic, address, idNumber, photo)>
<!ATTLIST passport id CDATA #REQUIRED>

<!-- Definition of simple elements -->
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT patronymic (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT idNumber (#PCDATA)>

<!-- Definition of photo element and its attributes -->
<!ELEMENT photo (#PCDATA)>
<!ATTLIST photo type (jpg|png|svg) #REQUIRED>

=== alextrukhin/web_module_1/Module_1_Lab_2_Trukhin_SE-324B/part3/passports.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="passports.xsl"?>
<!DOCTYPE passports SYSTEM "passports.dtd">

<passports>
    <passport id="1">
        <firstName>Oleksandr</firstName>
        <lastName>Trukhin</lastName>
        <patronymic>Vitaliiovych</patronymic>
        <address>Brovary, Kharkivska street 44</address>
        <idNumber>KB14298451</idNumber>
        <photo type="svg">https://placehold.co/500</photo>
    </passport>
    <passport id="2">
        <firstName>Oleksandr2</firstName>
        <lastName>Trukhin2</lastName>
        <patronymic>Vitaliiovych2</patronymic>
        <address>Brovary, Kharkivska street 45</address>
        <idNumber>KB14298452</idNumber>
        <photo type="svg">https://placehold.co/500</photo>
    </passport>
</passports>
